### Тренировочный тест

In [6]:
import pandas as pd
data=pd.read_csv('illiteracy.txt','\t')
data.head()
data.corr()

Illit    Births
Illit   1.000000  0.768663
Births  0.768663  1.000000

In [7]:
data.corr(method='spearman')

Illit    Births
Illit   1.000000  0.752962
Births  0.752962  1.000000

### 1 Тест

1 задание

In [10]:
data=pd.read_csv('water.txt','\t')
data.head()

location        town  mortality  hardness
0    South        Bath       1247       105
1    North  Birkenhead       1668        17
2    South  Birmingham       1466         5
3    North   Blackburn       1800        14
4    North   Blackpool       1609        18

In [11]:
data.corr()

mortality  hardness
mortality   1.000000 -0.654849
hardness   -0.654849  1.000000

In [14]:
#2 задание
round(data.corr(method='spearman'),4)

mortality  hardness
mortality     1.0000   -0.6317
hardness     -0.6317    1.0000

In [19]:
#3 задание
print(round(data[data['location']=='South'].corr(),4))
print(round(data[data['location']=='North'].corr(),4))

           mortality  hardness
mortality     1.0000   -0.6022
hardness     -0.6022    1.0000
           mortality  hardness
mortality     1.0000   -0.3686
hardness     -0.3686    1.0000


In [24]:
import math
#4 задание
#среди респондентов General Social Survey 2014 года хотя бы раз в 
#месяц проводят вечер в баре 203 женщины и 239 мужчин; реже, чем раз в месяц, это делают 718 женщин и 515 мужчин.
a=203 
b=718
c=239
d=515
korrm=(a*d-b*c)/math.sqrt((a+b)*(a+c)*(b+d)*(c+d))
korrm

-0.10900237458678963

In [29]:
#5 задание
from scipy import stats
stats.chi2_contingency([[a,b],[c,d]])

(19.40753078854304,
 1.0558987006638725e-05,
 1,
 array([[243.03402985, 677.96597015],
        [198.96597015, 555.03402985]]))

In [30]:
from statsmodels.stats import proportion

In [32]:
proportion.proportion_confint(a,a+b)

(0.19364133038884515, 0.24718385962201259)

In [33]:
proportion.proportion_confint(c,c+d)

(0.2837642337749763, 0.35018802086693357)

In [38]:
import scipy
z=scipy.stats.norm.ppf(0.05/2)
z

-1.9599639845400545

In [81]:
n1=a+b
n2=c+d
p1=a/n1
p2=c/n2

p_ob=(a+c)/(n1+n2)
p_left=p2-p1+z*math.sqrt((1-p1)*p1/n1+(1-p2)*p2/n2)
p1,p2,p_ob,n1,n2

(0.22041259500542887, 0.3169761273209549, 0.2638805970149254, 921, 754)

In [82]:
p_left

0.05390523321581314

In [84]:
p2-p1

0.09656353231552606

In [55]:
#7 задача
z_stat=(p1-p2)/math.sqrt(p_ob*(1-p_ob)*(1/n1+1/n2))
z_stat

-4.46111444482329

In [61]:
2*scipy.stats.norm.cdf(z_stat)

8.153453089573294e-06

In [65]:
#8 задача
scipy.stats.chi2_contingency?
#Не доволен	Более или менее	Доволен
#Не очень счастлив	197	111	33
#Достаточно счастлив	382	685	331
#Очень счастлив	110	342	333

In [67]:
import numpy as np
data=np.array([[197,111,33],[382,685,331],[110,342,333]])
data

array([[197, 111,  33],
       [382, 685, 331],
       [110, 342, 333]])

In [68]:
scipy.stats.chi2_contingency(data)

(293.68311039689746,
 2.4964299580093467e-62,
 4,
 array([[ 93.08597464, 153.74722662,  94.16679873],
        [381.6251981 , 630.318542  , 386.0562599 ],
        [214.28882726, 353.93423138, 216.77694136]]))

In [70]:
#10 задача
def cramers_stat(confusion_matrix):
    chi2 = scipy.stats.chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum()
    return np.sqrt(chi2 / (n*(min(confusion_matrix.shape)-1)))

result = cramers_stat(data)

In [71]:
result

0.2412013934500338

In [72]:
data.shape

(3, 3)