In [144]:
import pandas as pd
import numpy as np
from scipy import stats as scipy_stats
def writed(name,ans12):
    file=open(name,'w')
    file.write(str(ans12))
    file.close()

In [2]:
data=pd.read_csv('c4w41_gene_high_throughput_sequencing.csv')
data.head()

Patient_id Diagnosis  LOC643837  LOC100130417     SAMD11  \
0  STT5425_Breast_001_normal    normal   1.257614      2.408148  13.368622   
1  STT5427_Breast_023_normal    normal   4.567931     16.602734  42.477752   
2  STT5430_Breast_002_normal    normal   2.077597      3.978294  12.863214   
3  STT5439_Breast_003_normal    normal   2.066576      8.520713  14.466035   
4  STT5441_Breast_004_normal    normal   2.613616      3.434965  12.682222   

       NOC2L     KLHL17    PLEKHN1   C1orf170       HES4  ...      CLIC2  \
0   9.494779  20.880435  12.722017   9.494779  54.349694  ...   4.761250   
1  25.562376  23.221137  11.622386  14.330573  72.445474  ...   6.871902   
2  13.728915  14.543176  14.141907   6.232790  57.011005  ...   7.096343   
3   7.823932   8.520713   2.066576  10.870009  53.292034  ...   5.200770   
4  10.543189  26.688686  12.484822   1.364917  67.140393  ...  11.227770   

     RPS4Y1       ZFY      PRKY     USP9Y     DDX3Y       CD24  CYorf15B  \
0  1.257614  1.257614  1.257614  1.257614  1.257614  23.268694  1.257614   
1  1.815112  1.815112  1.815112  1.815112  1.815112  10.427023  1.815112   
2  2.077597  2.077597  2.077597  2.077597  2.077597  22.344226  2.077597   
3  2.066576  2.066576  2.066576  2.066576  2.066576  49.295538  2.066576   
4  1.364917  1.364917  1.364917  1.364917  1.364917  23.627911  1.364917   

      KDM5D    EIF1AY  
0  1.257614  1.257614  
1  1.815112  1.815112  
2  2.077597  2.077597  
3  2.066576  2.066576  
4  1.364917  1.364917  

[5 rows x 15750 columns]

In [3]:
data.describe()

LOC643837  LOC100130417     SAMD11      NOC2L     KLHL17    PLEKHN1  \
count  72.000000     72.000000  72.000000  72.000000  72.000000  72.000000   
mean    2.463922      7.100958  19.056151  15.618688  23.537120  11.303466   
std     1.413687      4.164703   9.287753   4.664146   4.475294   4.055122   
min     0.833898      1.231043   4.941211   6.395270   8.520713   2.066576   
25%     1.284642      3.892403  13.423946  12.574596  21.151624   8.712898   
50%     2.104677      6.315551  16.734855  14.586150  23.477006  11.172590   
75%     3.345067      8.916399  21.884325  17.695678  26.471909  13.568625   
max     7.364879     20.006038  60.584449  29.659104  34.110743  27.441093   

        C1orf170        HES4       ISG15        AGRN  ...      CLIC2  \
count  72.000000   72.000000   72.000000   72.000000  ...  72.000000   
mean    8.921396   63.270147   53.906324   70.678573  ...   5.563444   
std     3.270713   13.792140   45.635498   21.326237  ...   2.389789   
min     1.364917   42.544976   24.616767   42.631422  ...   1.144240   
25%     6.213396   53.093627   34.009687   54.202100  ...   3.805875   
50%     8.703397   63.230911   39.554954   65.510651  ...   5.617824   
75%    11.139240   69.880705   50.295756   79.427207  ...   7.100942   
max    17.121366  132.144503  327.590426  128.606260  ...  11.227770   

          RPS4Y1        ZFY       PRKY      USP9Y      DDX3Y       CD24  \
count  72.000000  72.000000  72.000000  72.000000  72.000000  72.000000   
mean    2.192029   1.967424   2.181360   1.729308   1.980733  16.834075   
std     2.454218   2.047129   2.542652   1.507149   2.230157   7.126802   
min     0.853957   0.853957   0.853957   0.833898   0.833898   4.675683   
25%     1.042783   1.011350   1.011350   1.003337   1.003337  11.186633   
50%     1.339507   1.273861   1.298543   1.252527   1.252527  16.514389   
75%     1.815754   1.647255   1.677971   1.625364   1.611299  21.849385   
max    11.913855  10.883310  11.692697  10.392539  10.640754  49.295538   

        CYorf15B      KDM5D     EIF1AY  
count  72.000000  72.000000  72.000000  
mean    1.825827   2.287380   1.756827  
std     1.902716   3.185571   1.623151  
min     0.833898   0.853957   0.833898  
25%     1.003337   1.011350   1.003337  
50%     1.252527   1.273861   1.252527  
75%     1.607345   1.647255   1.611299  
max     9.919132  17.278985   9.333904  

[8 rows x 15748 columns]

In [22]:
data.Diagnosis.value_counts()

early neoplasia    25
normal             24
cancer             23
Name: Diagnosis, dtype: int64

In [93]:
normal=data[data.Diagnosis=='normal'].iloc[:,2:]
cancer=data[data.Diagnosis=='cancer'].iloc[:,2:]
early_neoplasia=data[data.Diagnosis=='early neoplasia'].iloc[:,2:]

In [87]:
scipy_stats.ttest_ind(normal,early_neoplasia)
scipy_stats.ttest_ind(early_neoplasia,cancer)[1]

array([0.41676375, 0.65007209, 0.0674841 , ..., 0.53681403, 0.55976873,
       0.63243521])

In [88]:
pd.DataFrame?

In [89]:
pvalue=pd.DataFrame(index=[0,1],columns=data.columns[2:])

In [90]:
pvalue

LOC643837 LOC100130417 SAMD11 NOC2L KLHL17 PLEKHN1 C1orf170 HES4 ISG15 AGRN  \
0       NaN          NaN    NaN   NaN    NaN     NaN      NaN  NaN   NaN  NaN   
1       NaN          NaN    NaN   NaN    NaN     NaN      NaN  NaN   NaN  NaN   

   ... CLIC2 RPS4Y1  ZFY PRKY USP9Y DDX3Y CD24 CYorf15B KDM5D EIF1AY  
0  ...   NaN    NaN  NaN  NaN   NaN   NaN  NaN      NaN   NaN    NaN  
1  ...   NaN    NaN  NaN  NaN   NaN   NaN  NaN      NaN   NaN    NaN  

[2 rows x 15748 columns]

In [91]:
for i in data.columns[2:]:
    normal1=data[data.Diagnosis=='normal'][i]
    cancer1=data[data.Diagnosis=='cancer'][i]
    early_neoplasia1=data[data.Diagnosis=='early neoplasia'][i]
    pvalue.loc[0,i]=scipy_stats.ttest_ind(normal1,early_neoplasia1,equal_var = False)[1]
    pvalue.loc[1,i]=scipy_stats.ttest_ind(early_neoplasia1,cancer1,equal_var = False)[1]
pvalue

LOC643837 LOC100130417     SAMD11     NOC2L     KLHL17     PLEKHN1  \
0  0.690766  3.17853e-05  0.0602727  0.826429  0.0498762    0.144267   
1  0.413735     0.653429  0.0795556  0.287581   0.463292  0.00768133   

   C1orf170       HES4       ISG15       AGRN  ...     CLIC2    RPS4Y1  \
0  0.329108  0.0237124    0.240148  0.0379328  ...  0.463274  0.806008   
1  0.481306    0.57883  0.00074024   0.712687  ...  0.107366  0.458907   

        ZFY      PRKY     USP9Y     DDX3Y      CD24  CYorf15B     KDM5D  \
0  0.424543  0.740591  0.414922  0.640904  0.830134  0.670395  0.793925   
1  0.893433  0.467608  0.881584  0.659369  0.330617  0.542939  0.565753   

     EIF1AY  
0  0.661031  
1   0.63901  

[2 rows x 15748 columns]

In [57]:
ans1=(pvalue.loc[0,:]<0.05).sum()
ans1

1575

In [134]:
file=open('c4w4111.txt','w')
file.write(str(ans1))
file.close()

In [55]:
scipy_stats.ttest_ind?

In [135]:
ans12=(pvalue.loc[1,:]<0.05).sum()
ans12

3490

In [136]:
file=open('c4w4112.txt','w')
file.write(str(ans12))
file.close()

2 задача

In [59]:
import statsmodels.stats.multitest as ssm

In [63]:
pvalue.loc[0,:]

LOC643837          0.690766
LOC100130417    3.17853e-05
SAMD11            0.0602727
NOC2L              0.826429
KLHL17            0.0498762
                   ...     
DDX3Y              0.640904
CD24               0.830134
CYorf15B           0.670395
KDM5D              0.793925
EIF1AY             0.661031
Name: 0, Length: 15748, dtype: object

In [166]:
t=ssm.multipletests(pvalue.loc[0,:],0.05/2,method='holm')

In [167]:
t

(array([False, False, False, ..., False, False, False]),
 array([1, 0.500173682936049, 1, ..., 1, 1, 1], dtype=object),
 1.6076827300537389e-06,
 1.58750317500635e-06)

In [168]:
ans2=(t[1]<0.025).sum()
ans2

2

In [99]:
normal.mean(axis=0)/cancer.mean(axis=0)

LOC643837       1.226534
LOC100130417    0.533364
SAMD11          0.639844
NOC2L           0.933587
KLHL17          0.857168
                  ...   
DDX3Y           0.742138
CD24            1.085965
CYorf15B        0.730547
KDM5D           0.706167
EIF1AY          0.789922
Length: 15748, dtype: float64

In [133]:

means=pd.concat([normal.mean(axis=0), early_neoplasia.mean(axis=0),cancer.mean(axis=0)], axis=1, join='inner')
means.columns=columns=['normal', 'early_neoplasia','cancer']

means.loc[means.normal>means.early_neoplasia,'nor_neo']=means.normal/means.early_neoplasia
means.loc[means.normal<=means.early_neoplasia,'nor_neo']=means.early_neoplasia/means.normal

means.loc[means.early_neoplasia>means.cancer,'neo_can']=means.early_neoplasia/means.cancer
means.loc[means.early_neoplasia<=means.cancer,'neo_can']=means.cancer/means.early_neoplasia
means

normal  early_neoplasia     cancer   nor_neo   neo_can
LOC643837      2.681277         2.510894   2.186060  1.067858  1.148593
LOC100130417   4.368497         8.721781   8.190456  1.996517  1.064871
SAMD11        15.159566        18.531325  23.692614  1.222418  1.278517
NOC2L         15.374351        15.071854  16.468034  1.020070  1.092635
KLHL17        21.459886        24.152469  25.035813  1.125471  1.036574
...                 ...              ...        ...       ...       ...
DDX3Y          1.701654         1.961449   2.292908  1.152672  1.168987
CD24          17.106405        17.567902  15.752268  1.026978  1.115262
CYorf15B       1.576004         1.760707   2.157294  1.117197  1.225243
KDM5D          1.960442         2.151549   2.776173  1.097481  1.290314
EIF1AY         1.568210         1.727730   1.985272  1.101721  1.149064

[15748 rows x 5 columns]

In [169]:
ans21=sum(np.array((means.nor_neo)>1.5)& (t[1]<0.025) )
ans21

2

In [170]:
writed('c4w4121.txt',ans21)

In [172]:
sum(t[0])

2

In [176]:
t2=ssm.multipletests(pvalue.loc[1,:],0.05/2,method='holm')
sum(t2[0])

79

In [177]:
ans22=sum(np.array((means.neo_can)>1.5)& (t2[1]<0.025) )
ans22

77

In [178]:
writed('c4w4122.txt',ans22)

3 часть

In [180]:
ssm.multipletests?

In [192]:
t31=ssm.multipletests(pvalue.loc[0,:],0.05/2,method='fdr_bh')

In [193]:
t31[0].sum()

4

In [194]:
ans31=sum(np.array((means.nor_neo)>1.5)& (t31[0]) )
ans31

4

In [196]:
t32=ssm.multipletests(pvalue.loc[1,:],0.05/2,method='fdr_bh')
t32[0].sum()

832

In [197]:
ans32=sum(np.array((means.neo_can)>1.5)& (t32[0]) )
ans32

524

In [198]:
writed('c4w4131.txt',ans31)
writed('c4w4132.txt',ans32)