In [1]:
import numpy as np
from sklearn.datasets import fetch_20newsgroups

In [2]:
simple_dataset = fetch_20newsgroups(
    subset='train', 
    categories=['comp.sys.mac.hardware', 'soc.religion.christian', 'rec.sport.hockey'])

In [7]:
len(simple_dataset.data)

1777

In [19]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
vect=TfidfVectorizer(max_df=500, min_df=10)
X=vect.fit_transform(simple_dataset.data)
np.shape(X)

(1777, 3767)

In [9]:
from sklearn.cluster.hierarchical import AgglomerativeClustering

In [10]:
AgglomerativeClustering?

In [14]:
model=AgglomerativeClustering(n_clusters=3)

In [23]:
y_pred=model.fit_predict(X.toarray())

In [27]:
simple_dataset.target[0:20]

array([0, 0, 1, 2, 1, 0, 0, 0, 2, 0, 1, 0, 1, 0, 1, 0, 0, 2, 0, 1],
      dtype=int64)

In [29]:
y_pred[0:20]

array([2, 2, 0, 1, 0, 2, 2, 2, 1, 2, 0, 2, 0, 2, 0, 2, 2, 1, 2, 0],
      dtype=int64)

In [35]:
mapping = {2 : 0, 0: 2, 1: 1}
mapped_preds = [mapping[pred] for pred in y_pred]
print(float(sum(mapped_preds != simple_dataset.target)) / len(simple_dataset.target))

0.6961170512099043


In [36]:
from sklearn.cluster import KMeans

In [37]:
model=KMeans(n_clusters=3,random_state=1)

In [38]:
y_pred=model.fit_predict(X.toarray())

In [41]:
y_pred[0:20]

array([0, 0, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 0, 2, 0, 0, 1, 0, 2])

In [44]:
mapping={2:1,1:2,0:0}
y_pred_map=[mapping[pred] for pred in y_pred]
y_pred_map
print(float(sum(y_pred_map != simple_dataset.target)) / len(simple_dataset.target))

0.04727068092290377


In [45]:
import itertools
def validate_with_mappings(preds, target, dataset):
    permutations = itertools.permutations([0, 1, 2])
    for a, b, c in permutations:
        mapping = {2 : a, 1: b, 0: c}
        mapped_preds = [mapping[pred] for pred in preds]
        print(float(sum(mapped_preds != target)) / len(target))
        
validate_with_mappings(y_pred, simple_dataset.target, simple_dataset)

0.9707371975239167
0.6736072031513787
0.65053460889139
0.04727068092290377
0.9819921215531795
0.6758581879572313
